definitions:
  controllers.pingMessage:
    properties:
      message:
        type: string
    type: object
  models.BeerBox:
    properties:
      price_total:
        type: number
    type: object
  models.BeerItem:
    properties:
      brewery:
        type: string
      country:
        type: string
      create_at:
        type: string
      currency:
        type: string
      delete_at:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      update_at:
        type: string
    required:
    - brewery
    - country
    - currency
    - name
    - price
    type: object
info:
  contact: {}
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
paths:
  /v1/beers:
    get:
      consumes:
      - application/json
      description: You can list beers.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.BeerItem'
            type: array
      summary: List beers.
    post:
      consumes:
      - application/json
      description: You can create beer.
      parameters:
      - description: Create beers
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.BeerItem'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.BeerItem'
      summary: Create beers.
  /v1/beers/{beerID}:
    get:
      consumes:
      - application/json
      description: You can retrieve a beer.
      parameters:
      - description: Beer ID
        in: path
        name: beerID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BeerItem'
      summary: Retrieve a beer.
  /v1/beers/{beerID}/boxprice:
    get:
      consumes:
      - application/json
      description: You can Calculate Beer Boxes.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BeerBox'
      summary: Calculate Beer Box.
  /v1/ping/:
    get:
      consumes:
      - application/json
      description: Health API.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.pingMessage'
      summary: Health API.
swagger: "2.0"
